server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: signupModule
          uri: lb://signup
          predicates:
            - Path=/api/**
        - id: loginModule
          uri: lb://login
          predicates:
            - Path=/login/**
        - id: EmailOtpModule
          uri: lb://OTPService
          predicates:
            - Path=/email/**
        - id: SmsOtpModule
          uri: lb://OTPService
          predicates:
            - Path=/sms/**